name: Performance Test with Gatling

on:
  workflow_dispatch:
    inputs:
      userCount:
        required: true
        description: Max User Number
        default: '10'

      maxRunTime:
        required: true
        description: How long do you want to execute this test? Please state minutes.
        default: '2'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

      # setup maven and java
    - name: Setup Maven
      uses: stCarolas/setup-maven@v4.2

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run performance test
      env:
        USERS_COUNT: ${{github.event.inputs.userCount}}
        MAX_RUNTIME: ${{github.event.inputs.maxRunTime}}
        working-directory: ${{ github.workspace }}/${{ env.PERFORMANCE_TEST_FOLDER }}
      run: mvn gatling:test
